# Generated by Django 5.2.13 on 2026-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro_autores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, null=True, related_name='livros', to='core.autor'),
        ),
    ]
