# Generated by Django 5.2.13 on 2026-09-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_compra_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'PIX'), (4, 'Boleto'), (5, 'Transferência Bancária'), (6, 'Dinheiro'), (7, 'Cheque'), (8, 'Outro')], default=3),
        ),
    ]
