# Generated by Django 5.2.12 on 2026-09-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_compra_tipo_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenscompra',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_compra', to='core.livro'),
        ),
    ]
